# Xác định vị trí Nitrotyrosine  hóa trong protein

 Nguyễn Hồng Quang
 
 Khoa Kỹ thuật máy tính
 
 Trường Công nghệ thông tin và Truyền thông
 
 Trường Đại học Bách Khoa Hà Nội
 
 Tháng 12 / 2021

# Reference
https://www.mdpi.com/1422-0067/22/5/2704
 
Nilamyani, Andi N., Firda N. Auliah, Mohammad A. Moni, Watshara Shoombuatong, Md M. Hasan, and Hiroyuki Kurata. 2021. "PredNTS: Improved and Robust Prediction of Nitrotyrosine Sites by Integrating Multiple Sequence Features" International Journal of Molecular Sciences 22, no. 5: 2704. https://doi.org/10.3390/ijms22052704

# Bài toán:
Một chuỗi 41 ký tự với ký tự Y ở giữa

Ví dụ: ANTETTKVNGSLETKYRWTEYGLTFTEKWNTDNTLGTEITV

Cần dự đoán Y này có bị nitrat hóa hay không: phân lớp nhị phân chuỗi trên 

# Dataset
Tập dữ liệu training: 1191 positive samples and 1191 negative samples

Tập dữ liệu test: 203 positive samples and 1022 negative samples.

# Format file dataset
ANTETTKVNGSLETKYRWTEYGLTFTEKWNTDNTLGTEITV	sp|Q9Z2L0|	67	Y	+1	pssm1

In [8]:
file_train = "Training-datasets-PredNTS.txt"
file_test = "independent dataset-PredNTS.txt"

In [9]:
# dataset tổ chức như một dictionary, gồm có 2 keys: sequences và labels
# + sequences : là một list các sequences
# + labels: là một list các labels "+1" cho postive và "-1" cho negative
def read_file_dataset(file_dataset): 
    nb_positive = 0
    nb_negative = 0
    
    dataset = {}
    dataset["sequences"] = []
    dataset["labels"] = []
    
    f = open(file_dataset, "r")
    lines = f.readlines()
    f.close()
    
    print(lines[0])
    print("Tổng sô dòng trong file dataset: ", len(lines))
    
    for line in lines:
        pass
    
    print("Tổng số mẫu positive: ", nb_positive)
    print("Tổng số mẫu negative: ", nb_negative)
    
    return dataset
    
dataset = read_file_dataset(file_test)

ANTETTKVNGSLETKYRWTEYGLTFTEKWNTDNTLGTEITV	sp|Q9Z2L0|	67	Y	+1	pssm1

Tổng sô dòng trong file dataset:  1225
Tổng số mẫu positive:  0
Tổng số mẫu negative:  0

In [10]:
dataset = read_file_dataset(file_train)

EVPQLCSFILKTSQCTLKEVYGFNPEGKALLKKTKNSEEFA	sp|P04114|	103	Y	+1	pssm1

Tổng sô dòng trong file dataset:  2382
Tổng số mẫu positive:  0
Tổng số mẫu negative:  0

In [11]:
import pandas as pd

In [12]:
df1=pd.read_csv("Final-Fea-PUP-Fuse/CKSAAP.rfe200data.csv")
df2=pd.read_csv("Final-Fea-PUP-Fuse/aa.rfe400data.csv")
df3=pd.read_csv("Final-Fea-PUP-Fuse/bin.rfe300data.csv")
df4=pd.read_csv("Final-Fea-PUP-Fuse/kmer.rfe500data.csv")

In [4]:
df1

,Unnamed: 0,v441,v1323,v882,v1764,v1495,v2205,v1647,v939,v933,...,v1511,v113,v849,v1697,v1836,v1831,v1338,v1002,v1143,class
0,1,0.000,0.000000,0.000000,0.000000,0.027027,0.000000,0.027027,0.000000,0.000000,...,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.026316,yes
1,2,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.025,0.0,0.000000,0.0,0.000000,0.027027,0.0,0.026316,yes
2,3,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.027027,0.000000,0.026316,...,0.000000,0.000,0.0,0.027027,0.0,0.027778,0.000000,0.0,0.000000,yes
3,4,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.027027,0.0,0.000000,yes
4,5,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3602,3603,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,no
3603,3604,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.027027,0.000,0.0,0.000000,0.0,0.027778,0.027027,0.0,0.000000,no
3604,3605,0.050,0.000000,0.025641,0.000000,0.000000,0.000000,0.054054,0.026316,0.000000,...,0.027027,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,no
3605,3606,0.375,0.342105,0.358974,0.324324,0.000000,0.305556,0.054054,0.026316,0.000000,...,0.027027,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,no
3606,3607,0.475,0.447368,0.461538,0.432432,0.000000,0.416667,0.027027,0.000000,0.000000,...,0.027027,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,no

In [5]:
df2

,Unnamed: 0,v233,v34,v199,v176,v205,v237,v280,v154,v229,...,v132,v189,v427,v44,v434,v461,v496,v151,v46,class
0,1,205.80,1.96,1.14,0.03,-73,0.02,-106,0.58,4.68,...,-0.28,6.26,0.5,-0.0492,0.0728,-0.37,0.54,0.73,0.80,yes
1,2,300.46,3.93,0.94,-0.34,-106,0.32,189,9.36,0.58,...,0.32,4.36,2.3,0.1613,0.3113,-0.37,0.73,0.96,0.53,yes
2,3,174.06,0.94,1.96,-0.38,-20,0.05,-74,16.64,5.58,...,0.26,10.94,0.0,-0.0295,0.0126,-0.37,0.53,0.92,0.96,yes
3,4,233.21,16.64,16.64,0.13,145,-0.28,123,9.36,13.73,...,-0.17,4.36,0.0,0.3819,-0.0492,-0.04,0.92,0.96,0.80,yes
4,5,204.74,16.64,16.64,0.09,145,-0.41,-74,0.94,10.99,...,0.32,3.71,0.0,0.3819,-0.0053,0.03,0.96,0.53,0.42,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3602,3603,233.21,12.43,5.58,0.09,-70,-0.28,-70,0.94,13.73,...,-0.02,9.25,0.0,0.2947,-0.0589,0.19,0.63,0.42,0.77,no
3603,3604,341.01,12.43,0.47,-0.34,50,0.37,-106,0.94,0.27,...,0.18,10.94,0.0,0.2947,0.3557,-0.37,0.73,0.53,0.00,no
3604,3605,174.06,1.14,0.94,0.12,-78,0.05,-74,16.64,5.58,...,0.05,1.07,0.0,0.0126,-0.0053,-0.04,0.72,0.92,0.53,no
3605,3606,300.46,5.58,6.17,0.09,-13,0.32,-38,4.68,0.58,...,-0.28,6.26,0.0,-0.0282,0.0000,0.00,0.00,0.54,0.77,no
3606,3607,207.60,0.58,9.36,0.33,16,-0.17,123,0.94,12.43,...,0.05,3.50,0.0,-0.0053,0.0000,0.00,0.00,0.42,0.72,no

In [6]:
df3

,Unnamed: 0,v388,v220,v283,v241,v446,v262,v556,v331,v164,...,v828,v134,v648,v492,v99,v247,v271,v63,v268,class
0,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,yes
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,yes
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,yes
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,yes
4,5,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3602,3603,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,no
3603,3604,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,no
3604,3605,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,no
3605,3606,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,no
3606,3607,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,no

In [7]:
df4

,class,v9,v20,v5,v19,v15,v198,v6,v4,v16,...,v2666,v1061,v2036,v5327,v7689,v2456,v2376,v4017,v4198,v3298
0,yes,0.146341,0.024390,0.073171,0.00000,0.000000,0.0,0.048780,0.121951,0.073171,...,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.025
1,yes,0.097561,0.073171,0.024390,0.00000,0.048780,0.0,0.048780,0.097561,0.048780,...,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.000
2,yes,0.121951,0.048780,0.048780,0.00000,0.000000,0.0,0.024390,0.073171,0.048780,...,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.000
3,yes,0.024390,0.024390,0.024390,0.02439,0.048780,0.0,0.000000,0.048780,0.024390,...,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.000
4,yes,0.073171,0.024390,0.073171,0.00000,0.000000,0.0,0.048780,0.048780,0.097561,...,0.0,0.025,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3602,no,0.000000,0.024390,0.024390,0.04878,0.097561,0.0,0.121951,0.024390,0.048780,...,0.0,0.000,0.025,0.025,0.0,0.0,0.0,0.0,0.0,0.000
3603,no,0.073171,0.024390,0.024390,0.02439,0.048780,0.0,0.048780,0.097561,0.121951,...,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.000
3604,no,0.097561,0.073171,0.024390,0.00000,0.024390,0.0,0.048780,0.048780,0.170732,...,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.000
3605,no,0.073171,0.073171,0.000000,0.00000,0.024390,0.0,0.048780,0.024390,0.048780,...,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.000
3606,no,0.073171,0.073171,0.000000,0.00000,0.000000,0.0,0.048780,0.024390,0.024390,...,0.0,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.000

In [13]:
import numpy as np
k=4
4 ** np.arange(k-1, -1, -1)

array([64, 16,  4,  1], dtype=int32)